### ISSUE TITLE
Dead link in Oracle Database monitoring procedure

### ISSUE THREAD

**Issue by thibaults-centreon** [centreon/centreon-documentation#1410]
**Describe the bug**
dead link here:
https://github.com/centreon/centreon-documentation/blame/staging/versioned_docs/version-21.10/integrations/plugin-packs/procedures/applications-databases-oracle.md#L101
same for FR

to be replaced by:
https://www.oracle.com/fr/database/technologies/instant-client/linux-x86-64-downloads.html

**Comment by thibaults-centreon** [comment]
Bonus: There are also several typos in FR version that should be dealt with:
- ```Parcourir le fichier et exécuter la commande défini ci-dessous:```
- ```Ce compte utilisateur doit avoir la permission de lecture sur les tables suivants :```
-  ```Toujours dans l'interface Web Centreon, aller à la page Configuration > Hôstes et cliquer sur Ajouter. Remplir alors les champs du formulaires. Dans le champs Modèles cliquer sur + Ajouter une nouvelle entrée puis sélectionner App-DB-Oracle-custom. Une fois celui-ci configuré, certaines macros doivent être renseignées:```
(I may have missed some)

**Comment by cg-tw** [comment]
Closed by https://github.com/centreon/centreon-documentation/pull/1469

**Comment by cg-tw** [comment]
Closed by https://github.com/centreon/centreon-documentation/pull/1469
