### ISSUE TITLE
Dead link in mail configuration section

### ISSUE THREAD

**Issue by thibaults-centreon** [centreon/centreon-documentation#1678]
Dead link here:
https://github.com/centreon/centreon-documentation/blob/staging/versioned_docs/version-22.04/administration/postfix.md?plain=1#L8
(https://docs.centreon.com/docs/administration/postfix/)

Applies to versions 21.04, 21.10, 22.04, both EN & FR

**Comment by smau-centreon** [comment]
Fixed with https://github.com/centreon/centreon-documentation/pull/1681
