### ISSUE TITLE
Debian part missing

### ISSUE THREAD

**Issue by c0c0163** [centreon/centreon-documentation#1687]
Hi,

In the https://docs.centreon.com/docs/administration/secure-platform documentation it is missing all the debian part.
When can this be achieved?

Examples:
What is the equivalent on debian for etc/centreon/centreon.conf.php?
Also i found that the file /usr/share/centreon/config/centreon.config.php  is seeking for files that does not exist (lie 21-22).
Also, for debian, apache user is www-data, not apache

Same for the installation from packages, it seems the documentation for debian has been forked with no verification (i.e dnf does not exist on debian)

**Comment by lpinsivy** [comment]
Hi @c0c0163 you can find in our documentation how to install Centreon on Debian. Another PR will fixe some issue in the documentation.

For changes you can check [this article](https://thewatch.centreon.com/centreon-debian-user-group-46/differences-between-rhel-and-debian-installation-823).
