### ISSUE TITLE
Install from sources needs to be updated to use centreon-collect

### ISSUE THREAD

**Issue by vuntz** [centreon/centreon-documentation#2340]
The documentation to install from sources is outdated: https://docs.centreon.com/fr/docs/installation/installation-of-a-central-server/using-sources/

This mentions that centreon-clib and centreon-engine must be installed from their repos, but these repositories have been merged in centreon-collect now.

**Comment by smau-centreon** [comment]
Hi Vincent, your request is now handled by the documentation team.
Thanks for your feedback!

**Comment by cg-tw** [comment]
The topic has now been removed from the documentation as there seems hardly anyone uses it.
