### ISSUE TITLE
Filter some alarm  centreon_vmware_connector_client

### ISSUE THREAD

**Issue by DarkKnight9292** [centreon/centreon-documentation#3216]
Hello all,
Currently i want to exclude some alert  vCenter on Centreon, we know that this can be disable on vCenter but sadly that we don't manage it so it impossible.
 
here my command:

`/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=alarm-datacenter --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='vc353054'   --filter  --warning-status='%{status} =~ /yellow/i' --critical-status='%{status} =~ /red/i' --warning-total-alarm-warning='' --critical-total-alarm-warning='' --warning-total-alarm-critical='' --critical-total-alarm-critical='' --verbose --ignore-warn-msg --debug`

the output:
`checking datacenter 'EMEA-HCI2 Datacenter'
warning: alarm [yellow] [HostSystem] [abc3.abc3] [196714Z] High pNic error rate detected. Check the host's vSAN performance view for details/Default alarm to monitor 'pNic Error Rate'
critical: alarm [red] [HostSystem] [abc2.abc2] [974099Z] High pNic error rate detected. Check the host's vSAN performance view for details/Default alarm to monitor 'pNic Error Rate'
warning: alarm [yellow] [HostSystem] [abc1.abc1] [196935Z] High pNic error rate detected. Check the host's vSAN performance view for details/Default alarm to monitor 'pNic Error Rate'
`

but i don't want alarm related to pNic Error Rate appear on Centreon, how can i fix that ?
Thank you

**Comment by cg-tw** [comment]
Hello @DarkKnight9292,
Technically, this is not a documentation issue. Can you post your question on our community platform [The Watch](https://thewatch.centreon.com/)? More people will see your question and will be able to answer it.
Regards,
The documentation team.
