### ISSUE TITLE
Mikrotik SNMP page in the docs is missing something ?

### ISSUE THREAD

**Issue by MegaS0ra** [centreon/centreon-documentation#571]
Hi,

On this page 
https://docs.centreon.com/20.04/en/integrations/plugin-packs/procedures/network-mikrotik-snmp.html
It says to install the package centreon-plugin-Network-Mikrotik-Snmp with yum, which I did :
```
[root@monmaster ~]# yum install centreon-plugin-Network-Mikrotik-Snmp
Modules complémentaires chargés : fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.crazyfrogs.org
 * centos-sclo-rh: centos.crazyfrogs.org
 * centos-sclo-sclo: centos.crazyfrogs.org
 * epel: fr2.rpmfind.net
 * extras: centos.crazyfrogs.org
 * updates: centos.crazyfrogs.org
Résolution des dépendances
--> Lancement de la transaction de test
---> Le paquet centreon-plugin-Network-Mikrotik-Snmp.noarch 0:20210113-100416.el7.centos sera installé
--> Résolution des dépendances terminée

Dépendances résolues

==============================================================================================================================================================================================================================================
 Package                                                                 Architecture                             Version                                                      Dépôt                                                    Taille
==============================================================================================================================================================================================================================================
Installation :
 centreon-plugin-Network-Mikrotik-Snmp                                   noarch                                   20210113-100416.el7.centos                                   centreon-stable-noarch                                    64 k

Résumé de la transaction
==============================================================================================================================================================================================================================================
Installation   1 Paquet

Taille totale des téléchargements : 64 k
Taille d'installation : 450 k
Is this ok [y/d/N]: y
Downloading packages:
centreon-plugin-Network-Mikrotik-Snmp-20210113-100416.el7.centos.noarch.rpm                                                                                                                                            |  64 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installation : centreon-plugin-Network-Mikrotik-Snmp-20210113-100416.el7.centos.noarch                                                                                                                                                  1/1 
  Vérification : centreon-plugin-Network-Mikrotik-Snmp-20210113-100416.el7.centos.noarch                                                                                                                                                  1/1 

Installé :
  centreon-plugin-Network-Mikrotik-Snmp.noarch 0:20210113-100416.el7.centos                                                                                                                                                                   

Terminé !
```

Then, it says to add a host in Centreon, and to choose "Net-Mikrotik-SNMP-custom" in "Templates".
But this template does not exists.

Should the yum command be enough to create this template, or is there something more to do ?

Using Centreon 20.10.0 installed with the official iso.

Thank you

**Comment by Sims24** [comment]
Hi @MegaS0ra 

It depends on what kind of license you're using. 

If you have an IT-100 account or subscribe to an IT Online subscription: 
-  Install the Pack through the 'Configuration > Plugin Packs > Manager' menu.

If you're using an offline licensed version:
- Install this RPM: `yum install centreon-pack-network-mikrotik-snmp.noarch` 
- Install the Pack through the 'Configuration > Plugin Packs > Manager' menu.

The centreon-plugin packages the code while the centreon-pack one packages templates and all related centreon objects.

**Comment by MegaS0ra** [comment]
Hi @Sims24 

License ? I do not use any license I think, I only installed Centreon with centreon-20.10-0.el7.x86_64.iso

The package `centreon-pack-network-mikrotik-snmp` is not available on my Centreon setup :
```
[root@monmaster ~]# yum install centreon-pack-network-mikrotik-snmp.noarch
Modules complémentaires chargés : fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.pasteur.fr
 * centos-sclo-rh: ftp.pasteur.fr
 * centos-sclo-sclo: ftp.pasteur.fr
 * epel: fedora.cu.be
 * extras: ftp.pasteur.fr
 * updates: ftp.pasteur.fr
Aucun paquet centreon-pack-network-mikrotik-snmp.noarch disponible.
Erreur : Rien à faire
```

Through the 'Configuration > Plugin Packs' menu, when I search for "Mikrotik", I did found "Mikrotik SNMP".
But it only has a "Subscription" button, which takes me to https://store.centreon.com/en/

Is this a license-only feature ??

**Comment by Sims24** [comment]
Yes it is a 'license-only' feature.

With the Subsrciption button you can choose the IT-100 plan and it's free of charge! It will and let you monitor up to 100 Hosts and use any Plugin Pack you want on those.

**Comment by MegaS0ra** [comment]
As we monitor more than 100 hosts, activating this license may be a problem then... but thanks for your help !

I think the documentation should mention this need of a licence, and the Pack installation, right ?
Cause currently, it just says to install one package with yum, and that's all

**Comment by Sims24** [comment]
Yes, we are actually reviewing all monitoring procedures to have a more understandable format where it's made clear that at least an IT-Token is required. 

Check here https://docs.centreon.com/current/en/integrations/plugin-packs/procedures/cloud-azure-network-loadbalancer.html#overview / Setup section. 

Regards
