### ISSUE TITLE
Missing database schema

### ISSUE THREAD

**Issue by dalfo77** [centreon/centreon-documentation#771]
The new documentation miss the database schema.

Something like the schema in the old doc:

- https://docs.centreon.com/docs/centreon/en/19.04/faq/performance.html#databases-schema
- https://docs.centreon.com/docs/centreon/en/19.04/_images/centreon.png

Thanks,

**Comment by cg-tw** [comment]
We have decided not to include the schema in the documentation as it evolves too quickly and is difficult to present in a human-readable form.
